const model = {
    metronome: {
        timing: {
            upper: 3,
            lower: 4,
        },
        bpm: 80,
        metronomeOn: false,
    },
    chordsPage: {
        chordLetter: 'a',
        chordType: {
            major: true,
            minor: false,
            diminished: false,
            major7th: false,
            minor7th: false,
            dominant7th: false,
            suspended: false,
            augmented: false,
            extended: false,
            other: false,
        },
        allChords: {
            C: {
                major: [
                    {
                        startFret: 0,
                        EString: false,
                        aString: 3,
                        dString: 2,
                        gString: 0,
                        bString: 1,
                        eString: 0,
                    },
                ],
                minor: [
                    {
                        startFret: 3,
                        EString: false,
                        aString: false,
                        dString: 3,
                        gString: 3,
                        bString: 2,
                        eString: 1,
                    },
                ],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
            Csharp: {
                major: [
                    {
                        startFret: 1,
                        EString: false,
                        aString: 3,
                        dString: 2,
                        gString: 1,
                        bString: 2,
                        eString: 1,
                    },
                ],
                minor: [
                    {
                        startFret: 4,
                        EString: false,
                        aString: 1,
                        dString: 3,
                        gString: 3,
                        bString: 2,
                        eString: 1,
                    },
                ],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
            D: {
                major: [
                    {
                        startFret: 0,
                        EString: false,
                        aString: false,
                        dString: 0,
                        gString: 2,
                        bString: 3,
                        eString: 2,
                    },
                ],
                minor: [
                    {
                        startFret: 0,
                        EString: false,
                        aString: false,
                        dString: 0,
                        gString: 1,
                        bString: 3,
                        eString: 2,
                    },
                ],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
            Dsharp: {
                major: [],
                minor: [],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
            E: {
                major: [],
                minor: [],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
            F: {
                major: [],
                minor: [],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
            Fsharp: {
                major: [],
                minor: [],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
            G: {
                major: [],
                minor: [],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
            Gsharp: {
                major: [],
                minor: [],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
            A: {
                major: [],
                minor: [],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
            Asharp: {
                major: [],
                minor: [],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
            B: {
                major: [],
                minor: [],
                diminished: [],
                major7th: [],
                minor7th: [],
                dominant7th: [],
                suspended: [],
                augmented: [],
                extended: [],
                other: [],
            },
        }
    },
    createChordsPage: {
        newChord:
        {
            startFret: 0,
            EString: 0,
            aString: 0,
            dString: 0,
            gString: 0,
            bString: 0,
            eString: 0,
        },
    },
}